import type { Metadata } from "next";
import { LegalPageShell, LegalSection } from "@/components/legal/LegalPageShell";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Terms of Service — oscAr",
  description: "The terms governing your use of oscAr.",
};

export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated="July 17, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use
        of {LEGAL.serviceName} (the &quot;Service&quot;), a web application that
        helps you generate, audit, and deploy smart contracts to public
        blockchains. The Service is operated by {LEGAL.operator}, based in{" "}
        {LEGAL.jurisdiction}. By creating an account, connecting a wallet, or
        otherwise using the Service, you agree to these Terms. If you do not
        agree, do not use the Service.
      </p>

      <LegalSection heading="1. What oscAr is">
        <p>
          {LEGAL.serviceName} uses AI to generate ERC-20 smart contracts from
          your instructions, runs an automated security review, and lets you
          deploy the resulting contract to a blockchain of your choice. The
          Service is a self-service software tool. It is not a broker, exchange,
          wallet custodian, financial advisor, or law firm.
        </p>
      </LegalSection>

      <LegalSection heading="2. Non-custodial by design">
        <p>
          {LEGAL.serviceName} is non-custodial. You deploy contracts from your
          own wallet and pay your own network (gas) fees. We never take custody
          of your funds, your private keys, or the tokens or contracts you
          deploy. You are solely responsible for securing your wallet and keys.
          A deployed contract is controlled by you (or whoever you designate),
          not by us, and cannot be altered or reversed by us once it is live on
          a blockchain.
        </p>
      </LegalSection>

      <LegalSection heading="3. Eligibility and accounts">
        <p>
          You must be at least 18 years old and legally able to enter into these
          Terms. You are responsible for the accuracy of your account
          information and for all activity under your account. You must not
          share your credentials or let anyone else use your account.
        </p>
      </LegalSection>

      <LegalSection heading="4. Acceptable use">
        <p>You agree not to use the Service to:</p>
        <ul className="ml-5 list-disc space-y-1.5">
          <li>
            create or deploy tokens or contracts designed to defraud, such as
            honeypots, rug pulls, or contracts with hidden or misrepresented
            fees or owner powers;
          </li>
          <li>
            impersonate any person, project, or brand, or infringe anyone&apos;s
            intellectual property;
          </li>
          <li>
            issue unregistered securities or otherwise break the laws that apply
            to you in your jurisdiction;
          </li>
          <li>
            launder money, evade sanctions, or finance illegal activity; or
          </li>
          <li>
            abuse, overload, reverse-engineer, or attempt to circumvent the
            limits or security of the Service.
          </li>
        </ul>
        <p>
          Our automated safety filter refuses many such requests, but you remain
          fully responsible for what you generate and deploy, whether the filter
          catches it or not.
        </p>
      </LegalSection>

      <LegalSection heading="5. AI-generated code and audits">
        <p>
          Contracts are generated by AI and reviewed by an automated security
          analysis. This is a helpful aid, not a guarantee. Automated review can
          miss vulnerabilities, and a passing score does not mean a contract is
          safe, bug-free, or fit for any particular purpose. You are responsible
          for independently reviewing, testing, and — where the stakes warrant —
          obtaining a professional audit of any contract before deploying it or
          inviting others to interact with it. You deploy at your own risk.
        </p>
      </LegalSection>

      <LegalSection heading="6. Plans, billing, and payment">
        <p>
          Testnet deploys, AI generation, and security audits are free. A paid
          &quot;Pro&quot; subscription unlocks additional usage as described on
          our{" "}
          <a href="/pricing" className="text-accent-cyan hover:underline">
            pricing page
          </a>
          . Paid subscriptions are sold and processed by{" "}
          {LEGAL.merchantOfRecord}{" "}(&quot;Paddle&quot;), which acts as the
          merchant of record for these transactions. Your purchase is also
          subject to Paddle&apos;s buyer terms. Subscriptions renew
          automatically each billing period until cancelled. Refunds are handled
          under our{" "}
          <a href="/refunds" className="text-accent-cyan hover:underline">
            Refund Policy
          </a>
          .
        </p>
      </LegalSection>

      <LegalSection heading="7. Third-party services and blockchains">
        <p>
          The Service relies on third parties (including AI providers, RPC and
          data providers, wallet software, and payment processing) and on public
          blockchains we do not control. We are not responsible for outages,
          changes, fees, congestion, forks, or losses arising from those
          networks or providers. Blockchain transactions are irreversible.
        </p>
      </LegalSection>

      <LegalSection heading="8. No financial advice">
        <p>
          Nothing on the Service is financial, investment, tax, or legal advice.
          Digital assets are volatile and risky. Decisions you make about
          creating, deploying, buying, or selling tokens are yours alone.
        </p>
      </LegalSection>

      <LegalSection heading="9. Disclaimers">
        <p>
          The Service is provided &quot;as is&quot; and &quot;as available&quot;
          without warranties of any kind, whether express or implied, including
          fitness for a particular purpose, merchantability, and
          non-infringement. We do not warrant that the Service will be
          uninterrupted, error-free, or secure, or that generated contracts will
          be free of vulnerabilities.
        </p>
      </LegalSection>

      <LegalSection heading="10. Limitation of liability">
        <p>
          To the maximum extent permitted by law, {LEGAL.operator} will not be
          liable for any indirect, incidental, special, consequential, or
          punitive damages, or for any loss of funds, tokens, profits, or data,
          arising out of or relating to your use of the Service. Our total
          liability for any claim relating to the Service will not exceed the
          greater of the amount you paid us in the three months before the claim
          or fifty US dollars (USD 50).
        </p>
      </LegalSection>

      <LegalSection heading="11. Indemnity">
        <p>
          You agree to indemnify and hold harmless {LEGAL.operator} from any
          claims, damages, and expenses (including reasonable legal fees)
          arising from your use of the Service, the contracts or tokens you
          deploy, or your breach of these Terms or of any law.
        </p>
      </LegalSection>

      <LegalSection heading="12. Termination">
        <p>
          You may stop using the Service at any time. We may suspend or
          terminate your access if you breach these Terms or use the Service in a
          way that creates legal risk or harms others. Contracts you have already
          deployed are on-chain and remain unaffected by any account action.
        </p>
      </LegalSection>

      <LegalSection heading="13. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Material changes will be
          reflected by updating the &quot;Last updated&quot; date above.
          Continuing to use the Service after changes take effect means you
          accept the revised Terms.
        </p>
      </LegalSection>

      <LegalSection heading="14. Governing law">
        <p>
          These Terms are governed by the laws of {LEGAL.jurisdiction}, without
          regard to conflict-of-laws rules. Courts located in{" "}
          {LEGAL.jurisdiction} will have jurisdiction over any dispute, to the
          extent permitted by applicable law.
        </p>
      </LegalSection>

      <LegalSection heading="15. Contact">
        <p>
          Questions about these Terms? Contact us at{" "}
          <a href={`mailto:${LEGAL.contactEmail}`} className="text-accent-cyan hover:underline">
            {LEGAL.contactEmail}
          </a>
          .
        </p>
      </LegalSection>
    </LegalPageShell>
  );
}
